format = """╭─$directory$git_branch$git_status
$character """

[character]
success_symbol = "[╰─☸](bold cyan)"
error_symbol = "[╰─☸](bold red)"

[line_break]
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false
truncation_symbol = ""
home_symbol = "🏠"
